Resources:
  StudentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.studentsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  EnrollmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self.custom.enrollmentsTableName}
      AttributeDefinitions:
        - AttributeName: enrollmentId
          AttributeType: S
        - AttributeName: studentId
          AttributeType: S
        - AttributeName: semesterId
          AttributeType: S
      KeySchema:
        - AttributeName: enrollmentId
          KeyType: RANGE
        - AttributeName: studentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SemestersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.semestersTableName}
      AttributeDefinitions:
        - AttributeName: semesterId
          AttributeType: S
      KeySchema:
        - AttributeName: semesterId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
