Resources:
  StudentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.studentsTableName}
      AttributeDefinitions:
        - AttributeName: studentId
          AttributeType: S
      KeySchema:
        - AttributeName: studentId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SemestersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.semestersTableName}
      AttributeDefinitions:
        - AttributeName: semesterId
          AttributeType: S
      KeySchema:
        - AttributeName: semesterId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  TutorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tutorsTableName}
      AttributeDefinitions:
        - AttributeName: tutorId
          AttributeType: S
      KeySchema:
        - AttributeName: tutorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  CoordinatorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.coordinatorsTableName}
      AttributeDefinitions:
        - AttributeName: coordinatorId
          AttributeType: S
      KeySchema:
        - AttributeName: coordinatorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.contactsTableName} 
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: contactId
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: contactId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  EnrollmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.enrollmentsTableName}
      AttributeDefinitions:
        - AttributeName: semesterId
          AttributeType: S
        - AttributeName: enrollmentId
          AttributeType: S
      KeySchema:
        - AttributeName: semesterId
          KeyType: HASH
        - AttributeName: enrollmentId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
 