service: ticnsp-automations-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt.stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  studentsTableName: automations-students-${self:custom.stage}
  semestersTableName: automations-semesters-${self:custom.stage}
  enrollmentsTableName: automations-enrollments-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment:
    studentsTableName: automations-students-${self:custom.stage}
    semestersTableName: automations-semesters-${self:custom.stage}
    enrollmentsTableName: automations-enrollments-${self:custom.stage}

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ StudentsTable, Arn ]
        - "Fn::GetAtt": [ SemestersTable, Arn ]
        - "Fn::GetAtt": [ EnrollmentsTable, Arn ]

functions:
  - ${file(serverless/functions/semesters.yml)}
  - ${file(serverless/functions/enrollments.yml)}
  # - ${file(serverless/functions/students.yml)}

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(serverless/resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(serverless/resources/dynamodb-table.yml)}
  # S3
  - ${file(serverless/resources/s3-bucket.yml)}
  # Cognito
  - ${file(serverless/resources/cognito-user-pool.yml)}
  - ${file(serverless/resources/cognito-identity-pool.yml)}
